### ISSUE TITLE
Keys won`t save if /switch folder exists.

### ISSUE THREAD

**Issue by mattytrog** [shchmue/Lockpick_RCM#11]
`if (f_mkdir("sd:/switch")) {
        EPRINTF("Unable to create /switch folder on SD.\nAttempting save regardless.")
    }`

Quick dirty fix.

**Comment by Conan179** [comment]
#12 its the same.

**Comment by mattytrog** [comment]
Just an oversight I`m 100% sure.

Just prevent it freeing buffers if !FR_OK

**Comment by shchmue** [comment]
all set, thanks everyone 340a25651825e4ed3267dbc9f1ab0124a6a882ae
