### ISSUE TITLE
Unable to mount system partition on firmware 9.0.1

### ISSUE THREAD

**Issue by Frefreak** [shchmue/Lockpick_RCM#14]
During the process it errors about something like "not fatfs" followed by an "Unable to mount system partition". `prod.keys` is generated with 136 keys but no `title.keys`. Also sd_seed seems to be missing. (there're 4 keys started with "sd_card" though).

how I made the sd:
Use sdsetup and selected a few components, download zip, extract and copy `sd/*` to sd card, `libsys_minerva.bso` is in `bootloader/sys/` and `/sept` with `payload.bin`, `sept-primary.bin`, `sept-secondary.bin` and 2 `.enc` files.

I'm aware of this issue (#13) but in my case this particular sd has already booted with OFW many times, and from the error message this must be another issue.

BTW: my bis_key_02 and 03 is the same, is this expected? I tried to use ninfs to mount my rawnand.bin but the generated `.img` file seems to be invalid.

**Comment by shchmue** [comment]
bis keys 02 and 03 the same is right, yeah. sd_seed and titlekeys both need nand access and it sounds like they're having trouble getting that. are you using the latest lockpick_rcm? last i check sdsetup's version was out of date :x

**Comment by Frefreak** [comment]
I tried both the payload included in sdsetup and the latest downloaded from release page. (checked they are different). I only use sdsetup to populate my sd card but launched lockpick_rcm via `fusee_launcher`. Do I need a newer version of **/sept** files and **libsys_minerva.bso** etc? I will try setting up my sdcard manually later.

**Comment by shchmue** [comment]
you do need the latest version of those

**Comment by Frefreak** [comment]
hi just tried with **atmosphere-0.9.4-master-a750e55f+hbl-2.2+hbmenu-3.1.1.zip
** and ** hekate_ctcaer_5.0.2_Nyx_0.8.2.zip
** (both currently newest release) but still not work. Any idea why its failing to access nand... I assume I don't need to boot the cfw, just launch the payload should work right?

here is how my sd card looks like now:
```
λ ~/switch_tools ls /Volumes/Untitled/
Nintendo   atmosphere bootloader hbmenu.nro sept       switch
```

**Comment by Frefreak** [comment]
While I still can't get it works, there's no real progression here, we can close this issue for now. I will add comment here if I get any news in the future.

**Comment by shchmue** [comment]
Was this on Sysnand or Emunand? Have you tried the new version, 1.8.0?
