### ISSUE TITLE
9.1.0 - Unknown pkg1 version

### ISSUE THREAD

**Issue by nickkeane** [shchmue/Lockpick_RCM#15]
Getting the above message when running Lockpick_RCM on a recently-updated switch.

**Comment by shchmue** [comment]
yeah 9.1.0 will not be supported until after Sept is updated and I update this

**Comment by nickkeane** [comment]
https://github.com/Atmosphere-NX/Atmosphere/issues/706

**Comment by shchmue** [comment]
yes. i’ll probably push an update tomorrow.

**Comment by ravi1913** [comment]
Hey @shchmue don't mean to rush you or anything, I completely understand it takes time. Any estimate on when you'll be done? Or if you could tell me what to change, I don't mind trying it out.

**Comment by shchmue** [comment]
I have the changes done locally, but I am waiting on a bugfix from Hekate as it makes using Lockpick potentially annoying: https://github.com/CTCaer/hekate/issues/319

**Comment by ravi1913** [comment]
No worries! Thanks for the prompt reply, I'll wait.

**Comment by ravi1913** [comment]
For people not using Hekate, is the bug fix we're waiting on relevant?

**Comment by shchmue** [comment]
it will cause problems for anyone with old hekate files, so i'm not inclined to release something half-functional just to replace it again soon after

**Comment by shchmue** [comment]
https://github.com/shchmue/Lockpick_RCM/commit/a9595e58376c359e385f9fc931de7b63b626a820

**Comment by Xehanort88** [comment]
Just to clarify, it is still not possible to use this in latest firmware, is it?

**Comment by shchmue** [comment]
It works on 9.1.0

**Comment by Xehanort88** [comment]
Not for me, unfortunately.  It does give the same error.

**Comment by shchmue** [comment]
If it's in sysnand, you're either not injecting the newest version, or your BOOT0 is corrupt (the console wouldn't be able to boot)
If emunand, the emummc.ini config has the wrong offset for your pkg1 (it wouldn't be able to boot emunand with hekate)
Your sept folder might also be out of date

**Comment by Xehanort88** [comment]
That's what the problem was - the downloaded didn't detect your new version.
Thank you so much, my 2 keys files have been found and safely stored with
backup!

Il giorno gio 23 gen 2020 alle ore 14:53 shchmue <notifications@github.com>
ha scritto:

**Comment by Folke137** [comment]
Same thing again on the new update

**Comment by shchmue** [comment]
will be fixed soon https://github.com/shchmue/Lockpick_RCM/issues/23

**Comment by Hrozhek** [comment]
Looks like an issue at 11.0.0

**Comment by Poincare1** [comment]
Hello, it is 2021 and this error still exists on v11.0 for sysnand and emummc, 
"Getting bis_keys...
Unknown pkg1 version."  

Apparently whatever the fix was has not been fixed.  

Is there a way to correctly execute Incognito for v11.0?

**Comment by sthetix** [comment]
I assume your boot0 is damaged, maybe you ever used choidujournx to update the firmware. for incognito, you can create a file called exosphere.ini (text file), and paste this code below

[exosphere]
debugmode=1
debugmode_user=0
disable_user_exception_handlers=0
enable_user_pmu_access=0
blank_prodinfo_sysmmc=1
blank_prodinfo_emummc=1
allow_writing_to_cal_sysmmc=0

reboot or boot ur console and check if the serial number is now blank (fullnof zeros)
