### ISSUE TITLE
Blank screen when running payload

### ISSUE THREAD

**Issue by ckurtz22** [shchmue/Lockpick_RCM#16]
Downloaded the latest release payload, whenever I run it either via Hekate chainloading or via fusee-gelee it just leaves me with a blank screen

**Comment by ckurtz22** [comment]
Tried various release versions, this issue happens on v1.8.1 and v1.8.0. Versions prior work fine.

**Comment by shchmue** [comment]
do you have all the hekate 5.1.1 files on SD?

**Comment by ckurtz22** [comment]
Hmm that's probably it. I assumed that it was a standalone application and haven't really been up to date for the past 6 months.
