### ISSUE TITLE
Black screen after Sept

### ISSUE THREAD

**Issue by shchmue** [shchmue/Lockpick_RCM#17]
Had a report about this and they verified it does not happen for the Sept restart that Hekate pkg2 dump does

**Comment by reefbarman** [comment]
I'm not sure if its related, but when I try to niject the Lockpick_RCM.bin, the screen goes black, i can then inject another payload like helkate but I can not get lockpick_RCM to work. My console is on 9.1.0 using the latest atmosphere

**Comment by shchmue** [comment]
The original reported issue was resolved by an intermediate update
