### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Alexowo** [shchmue/Lockpick_RCM#19]
I just updated to 9.1.0 from 8.1.0 (offline obviously), got the latest version of atmosphere and tried using Lockpick_RCM, nothing was outputted, just a black screen, I'm assuming it's supposed to show graphics at some point but nothing happens apart from showing a black screen when I inject the payload. Any ideas?

**Comment by ceriphim** [comment]
I'm having the same problem. Booted payload via both Hekate and TegraRcmGUI. Payload will boot, but pressing the power button to dump keys results in a black screen. Have to perform a hard reset to get out of it.
I'm on 9.1.0.

**Comment by shchmue** [comment]
Are the files in the sept folder in the latest Atmosphere release zip on your SD?

**Comment by ceriphim** [comment]
Yes, however I was using the Kosmos repack and it appears that downloading the latest version directly from the Atmosphere repository and replacing the files from the Kosmos package with those found in the Atmosphere repo has solved the issue I was experiencing. There may be an issue with the files in the Kosmos repo or my files in particular may have become corrupt in some way. Either way, not a problem with this Lockpick_RCM release itself.

**Comment by shchmue** [comment]
sounds like older sept files. reopen if persists
