### ISSUE TITLE
10.0.0 support / remap bugfix

### ISSUE THREAD

**Issue by NotReallyConnor** [shchmue/Lockpick_RCM#23]
When I try to use lockpick 1.8.1 on sysNAND on the latest switch version it gives me the error unknown pkg1 version.
Are you currently working on an update for this?

**Comment by shchmue** [comment]
i am. there's a nastier bug involved that needs addressing first, i will push a release when everything is ready.

**Comment by NotReallyConnor** [comment]
great to hear that you're already working on it, good luck :)

**Comment by shchmue** [comment]
fixed in https://github.com/shchmue/Lockpick_RCM/commit/8a742a45d4963aa9d0332f5a9e3dfbe4ace5a262 and https://github.com/shchmue/Lockpick_RCM/commit/ef6676d3b9148147e2e64364ef8cfc219225a4c9
