### ISSUE TITLE
Needs fss0 support

### ISSUE THREAD

**Issue by pabermod** [shchmue/Lockpick_RCM#24]
Using NEUTOS Atmosphere fork:
https://github.com/borntohonk/NEUTOS/releases

Lockpick_rcm is not working due to missing filesin /sept/folder.
Those files are not needed to boot atmosphere, as they are embedded into fusee-secondary

**Comment by shchmue** [comment]
true, i should add fss0 parsing to this

**Comment by StiefelHD** [comment]
> 
> 
> true, i should add fss0 parsing to this

i have the same problem. cant get the keys..

**Comment by shchmue** [comment]
now supported 4a69ea192232cb0e0967eea05c8a19bc5bf18a79
