### ISSUE TITLE
v1.8.2 unable to derive package2 key missing FS keys

### ISSUE THREAD

**Issue by btcioner** [shchmue/Lockpick_RCM#26]
some info:
Keyblob 0 corrupt
Keyblob 1 corrupt
Keyblob 2 corrupt
.......
unable to derive package2 key 
missing FS keys, Skipping ES/SSL keys

**Comment by shchmue** [comment]
try version 1.8.3. does this switch boot? if nand is hosed, there's not much it can do

**Comment by shchmue** [comment]
closing for now, comment again if problems persist
