### ISSUE TITLE
blackscreen with horizon 10.0.2

### ISSUE THREAD

**Issue by n3o33** [shchmue/Lockpick_RCM#27]
after loading the payload nothing happens. i allways got an blackscreen.

**Comment by n3o33** [comment]
ps. using newset 1.8.2

**Comment by deadair3210** [comment]
unless I missed a release, this doesn't support 10.0.2 yet

**Comment by shchmue** [comment]
it does support 10.0.2. black screens are most often caused by:
- chainloading from SX loader
- using old Hekate SD files

**Comment by deadair3210** [comment]
My bad. Was thinking of another project, just tried it on mine and it works fine

**Comment by n3o33** [comment]
thx for fast reply. gonna trying with a fresh sd card.
