### ISSUE TITLE
Doesn't work anymore in FW 10.0.4 AMS 0.13.0

### ISSUE THREAD

**Issue by sebbe1985** [shchmue/Lockpick_RCM#29]
I have always used Lockpick_RCM without problems up until latest FW. 
Now I'm getting the following errors:
1. Unable to derive Package2 key.
2. Missing FS keys. Skipping ES/SSL keys.

What could be wrong?

![20200616_225043](https://user-images.githubusercontent.com/62074901/84894717-85d87480-b0a1-11ea-9e92-2072e85d4bb8.jpg)

**Comment by Leo-Sag** [comment]
I am facing the same issue for SwitchOS 10.0.4 and Lockpick_RCM 1.8.3.
I tried both Atmosphere 0.13.0 and 0.12.0. However, this cannot run correctly...

**Comment by sebbe1985** [comment]
> I am facing the same issue for SwitchOS 10.0.4 and Lockpick_RCM 1.8.3.
> I tried both Atmosphere 0.13.0 and 0.12.0. However, this cannot run correctly...

Sorry but I'm glad to hear that, then it's just not me :)

**Comment by shchmue** [comment]
is everyone having problems on sysmmc or emummc or both?

**Comment by shchmue** [comment]
i was able to reproduce this with atmosphere 13. will investigate

**Comment by sebbe1985** [comment]
> is everyone having problems on sysmmc or emummc or both?
> 
> edit: and does the mode you're dumping keys for boot cfw successfully?

Problem on both, and cfw boots successfully.
Just saw that you could reproduce it, good!

Good luck :)

**Comment by Leo-Sag** [comment]
I have a problems on symmc. Another switch which run Emummc, can be run successfully.

**Comment by shchmue** [comment]
easy fix, sept made a breaking change. https://github.com/shchmue/Lockpick_RCM/commit/47f749c6feedf2fc90a9d7a4f67f9ecd87436922

**Comment by Leo-Sag** [comment]
Fixed on my environment! 
Thank you for your kindly/rapidly support!

**Comment by msdos** [comment]
> is everyone having problems on sysmmc or emummc or both?

sysmmc on an old firmware working. Having the error on emummc.

I was having exatcly the same problem described in this issue.

I was using https://github.com/Team-Neptune/DeepSea/releases/tag/v1.4.1, a day _before_ you made this fix, and was using the Lockpick_RCM payload from their package: thus having the same error.

I've manually updated the payload to be used from Hekate. And they have a new release too with the fix (https://github.com/Team-Neptune/DeepSea/releases/tag/v1.4.2). It's working here.
