### ISSUE TITLE
BIS keys iPatched Consoles

### ISSUE THREAD

**Issue by yoboto** [shchmue/Lockpick_RCM#32]
Not really a bug just a question for the Dev.

I am Seeing conflicting reports on wether lockpick RCM is safe for use on ipatched console with SX-core installed, some people are saying it could cause a brick,  others are saying the BIS Keys won't be produced or that the keys won't be valid, your v1.8.1 indicates this issue may have been resolved but i am unsure, can you confirm?

I have a situation where i have three ipatched boards which won't boot horizon, but they will happily boot Hekate and Ubuntu with SX-Core and don't appear to have any hardware related issues, i think they may have a software related issue and require keys for ChoiDujour OS recreation. If this feature has not been implemented and you require a tester I'd be happy to help...... not much to lose with these boards.

Either way, thanks for the program and all the effort thus far :)

**Comment by shchmue** [comment]
It should work on an Erista console, but probably won't work on a Mariko one
