### ISSUE TITLE
Payload boot support for Mariko + SX Core

### ISSUE THREAD

**Issue by papajeezus** [shchmue/Lockpick_RCM#33]
Requesting support to be able to boot from 3.0.5 SX OS with SX Core for full dump of keys.

**Comment by shchmue** [comment]
As soon as Hekate supports Mariko, I will include Mariko support. I don't personally know how hwinit works and rely on that codebase for it.

**Comment by toratti** [comment]
Thanks for the reply, I'll leave it open waiting, close you so wish.

**Comment by override182** [comment]
Waiting for this as well. Hope it comes :(

**Comment by shchmue** [comment]
I've made some progress on this but I want to make sure it's perfect before releasing.

**Comment by shchmue** [comment]
Done. https://github.com/shchmue/Lockpick_RCM/commit/a0eaa5e4edc4ef317f2daa5724a55f6769529545
