### ISSUE TITLE
error messages everywhere!

### ISSUE THREAD

**Issue by naldo29** [shchmue/Lockpick_RCM#34]
hi, im using sx os on the lates beta on fw 10.1.0 ans sysnand on latest rn and when i try to dump my sysnand i get so many error messages, and ofcourse, cannot get my syskey but i can get my product key.

**Comment by shchmue** [comment]
what error messages

**Comment by naldo29** [comment]
> what error messages

![image](https://user-images.githubusercontent.com/35706559/93687355-3b450a80-fa8b-11ea-9f72-41d031d87549.png)

**Comment by shchmue** [comment]
download the Atmosphere release zip and copy the `sept` folder to your SD, then run again

**Comment by naldo29** [comment]
yeah, that was it thx!
