### ISSUE TITLE
unable to init MMC

### ISSUE THREAD

**Issue by darodi** [shchmue/Lockpick_RCM#35]
Hello,

A few days ago, I used Lockpick RCM to dump my keys on firmware 8.0.1. It was working fine.
Then I updated my firmware to version 10.2 and now "key generation unk" is displayed for my sysNAND and I'm getting this strange error.

Is lockpick RCM working with firmware 10.2?
Is this something else?

Thanks in advance for your help.

![IMG_20201118_192928_small](https://user-images.githubusercontent.com/4682830/99577468-ad7a9280-29db-11eb-99a1-7d24d6cfe2da.jpg)
![IMG_20201118_193055_small](https://user-images.githubusercontent.com/4682830/99577506-be2b0880-29db-11eb-9042-9b20b5f8577c.jpg)

**Comment by shchmue** [comment]
This has triggered fallback code in Hekate which indicates the SD reader is losing connection to the motherboard. Does Hekate work? Can you boot CFW? Does the SD work in the OS?

**Comment by darodi** [comment]
Hekate was working but I could not boot CFW.
I replaced my atmosphere files on the SD card and now Lockpick RCM is working again.
Thanks a lot
