### ISSUE TITLE
Missing keys on prod.keys

### ISSUE THREAD

**Issue by albertodev01** [shchmue/Lockpick_RCM#36]
Hello!

When I used Lockpick_RCM 2 years ago, it gathered 160 keys.
I have used it again today with my new switch (firmware 10.2, latest) and it's only extracting 81 keys.

When I ran Hactool in the old console (160 keys in file), I was able to encrypt and decrypt save files.
When I run Hactool in the new console (81keys in file), I am able to decrypt but NOT to encrypt because keys are missing.

Is this because the file still has tu support the latest OS?

**Comment by shchmue** [comment]
can you confirm that you are using the latest release of lockpick_rcm? does your console boot? and can you either post a photo of the screen when it is finished dumping keys or duplicate any progress messages that appear here?

**Comment by albertodev01** [comment]
It was probably a stupid mistake on my side. I removed the `sept/` folder and re-downloaded it witht he latest atmosphere release.
I should have tried it before opening an issue.

It works!
