### ISSUE TITLE
Version 11.0

### ISSUE THREAD

**Issue by Zeyzers** [shchmue/Lockpick_RCM#37]
I wrongly updated my 2nd switch to 11.0 and lockpick doesn't work. I'm new and i would ask how much it take to the newer version of lockpick.
I dont want to hack the other switch cause i have all games and i don't want risk.
I didn't know where to post it. I'm sorry

**Comment by Masamune3210** [comment]
Just boot without atmos for the time being if you are really desperate to play your games? If you can't play your games without atmos, stop asking for help when pirating

**Comment by shchmue** [comment]
11.0 support shouldn't take too long. Running Lockpick_RCM doesn't affect anything on your NAND though, for what it's worth

**Comment by shchmue** [comment]
https://github.com/shchmue/Lockpick_RCM/commit/bd134cf670822880ac55b3192bfcb949aa176ec7
