### ISSUE TITLE
Latest update stuck on Lockpick text screen.

### ISSUE THREAD

**Issue by mrdude2478** [shchmue/Lockpick_RCM#4]
Under 6.20 - lockpick no longer dumps keys with the latest update.  The screen when loading only shows the lockpick txt - but freezes instantly, and does not dump any keys. Previous version worked fine.

**Comment by shchmue** [comment]
How are you loading it, pushing directly or chainloading?

**Comment by mrdude2478** [comment]
Chainloading - it was working like that before.

**Comment by shchmue** [comment]
chainloading from what?

**Comment by mrdude2478** [comment]
Argon-nx, I've switched back to the previous version now.

**Comment by shchmue** [comment]
I think I found the problem and it only effects 6.2.0. I'll investigate later today.

**Comment by mrdude2478** [comment]
OK, thanks very much - I'll check later and see if you managed to fix. I don't plan on updating sysnand above 6.20 for now, I am using emunand on 7.01. Thanks for looking though.

**Comment by shchmue** [comment]
fixed in e1ffda6ab953d5c797b4ae2007944d6a1885deb9 :)

**Comment by mrdude2478** [comment]
Thanks for fixing, it's working fine now :-) 👍
