### ISSUE TITLE
Crash/Hang when extracting Titlekeys (Unexpected remap entry chain failure)

### ISSUE THREAD

**Issue by Lollyde** [shchmue/Lockpick_RCM#41]
Lockpick_RCM hangs completely at the Titlekeys step until hard reset on both emummc (10.1.0) and sysmmc (11.0.0).
Injected payload both through Hekate and directly, same result each time.

![IMG_20201206_004218_0](https://user-images.githubusercontent.com/11347524/101267741-7edf1480-375c-11eb-8033-4a57bc3c3c71.jpg)

**Comment by twotonedearly** [comment]
I too get the same error

**Comment by shchmue** [comment]
This is bizarre but apparently not uncommon. I'll look into it, thank you for letting me know.

**Comment by Lollyde** [comment]
I'm trying to test different commits to see if I can find the commit that causes this error, however I'm getting a compile error about a missing `libs/nx_savedata/save.h`. I've not compiled anything for the switch before so I'm not sure where this error might come from - I've followed the instructions to install `switch-dev devkitARM devkitarm-rules`

**Comment by shchmue** [comment]
the commit will just be the monolithic save handler overhaul, so if you fix that header it will probably work on < 11.2.0 but there's nothing intermediate to check really

**Comment by Lollyde** [comment]
Hm yeah, makes sense - if you need someone to test a new build I'd be happy to help tho!

**Comment by jamal2362** [comment]
same error
![IMG_20201206_125544__01](https://user-images.githubusercontent.com/15986930/101279603-97cee080-37c3-11eb-84a8-4631e9652d6e.jpg)

**Comment by JonathanaAcalAlvarado** [comment]
Hello, I have the same problem, please could you help me with this issue, thanks

**Comment by anivay** [comment]
I am also having same error

**Comment by snickettags** [comment]
I have received this error also; it happened when selecting 'Dump from SysNAND'. It asks to ensure I am using the most recent version. Thanks for looking into this.

**Comment by buenokevin200** [comment]
Hi there, i've been following the development of this code. I'm using Lockpick RCM 1.8.5 in an 11.0.0 firmware's Switch and i'm having the same error.

**Comment by Lollyde** [comment]
Unless there is more info you have that isnt posted in the issue yet, "I have the same error" just clogs up the inbox - you could instead use reacts to massages

**Comment by shchmue** [comment]
Yeah as it stands this is going to be a tricky bug and I have testers so I don't need any more feedback about how prevalent the bug is at this time

**Comment by shchmue** [comment]
Fixed in https://github.com/shchmue/Lockpick_RCM/commit/1b5a7bb302d6506d7c38203cb62e8e296d997970
