### ISSUE TITLE
Error pkg1 in v.1.8.5 using hekate, worse using sx os

### ISSUE THREAD

**Issue by Natillax** [shchmue/Lockpick_RCM#42]
Hi I would like to report that I couldn't took my keys because an error called Pkg1 using Hekate. It's even worse using sx os because it says 'MMC unit done, Unable to backup payload.bin').
I'm not using Mariko and I'm in FW 11.0.0.

Thanks for your attention.

**Comment by shchmue** [comment]
does your console boot?

**Comment by Natillax** [comment]
Yes, of course.

**Comment by shchmue** [comment]
Is this with sysmmc or emummc?

**Comment by Natillax** [comment]
I don't use emunand (emummc), so... i guess it's sysmmc.

**Comment by shchmue** [comment]
Give the new version a try and let me know.

**Comment by shchmue** [comment]
Closing until response
