### ISSUE TITLE
Unexpected remap entry chain failure

### ISSUE THREAD

**Issue by vincentwaffle** [shchmue/Lockpick_RCM#43]
![96351021-40AE-43F8-A378-CE7D08BCE8F6](https://user-images.githubusercontent.com/838123/101278130-03b04980-37c2-11eb-98c2-0bbf95bd14f5.jpeg)

Trying to write 11.0 keys

**Comment by deejay87** [comment]
I have test and same error

**Comment by jamal2362** [comment]
same error

![IMG_20201206_125544__01](https://user-images.githubusercontent.com/15986930/101279456-b08ac680-37c2-11eb-8d87-3f37ace0540c.jpg)

**Comment by muxi1** [comment]
This problem seems to exist in general, not only under FW 11.0.0, because I wanted to test it under FW 10.2.0 with the same result.

**Comment by buenokevin200** [comment]
Hi there, my switch have the 11.0.0 firmware, having the same problem

![hola](https://user-images.githubusercontent.com/73407824/101286747-abc61280-37c2-11eb-9388-51e5271d8356.PNG)

**Comment by jnafml** [comment]
me aswell, also having this issue

**Comment by squirrellyidiot** [comment]
Commenting to say I also have the same issue on 11.0, unpatched model :(

**Comment by xalker42** [comment]
![20201207_022401](https://user-images.githubusercontent.com/75598062/101307118-53058100-3879-11eb-8625-029ff2ffd997.jpg)
another one T_T on clear 11.0.0

**Comment by JonathanaAcalAlvarado** [comment]
Hola, Tengo el mismo error al momento de cargar los archivos para las keys en la version 11.0.0, alguien sabe como podemos arreglar esto para obtener las keys
![WhatsApp Image 2020-12-07 at 9 12 30 PM](https://user-images.githubusercontent.com/75388344/101436180-401f9a80-38d3-11eb-8a32-34ff6dbac13a.jpeg)

**Comment by shchmue** [comment]
still working on it, going to keep these all in a single issue: https://github.com/shchmue/Lockpick_RCM/issues/41
