### ISSUE TITLE
why it shows unexpected remap entry chain failure  for dumping in switch 11.0.0?

### ISSUE THREAD

**Issue by paulzheng136** [shchmue/Lockpick_RCM#44]
i download the lockpick rcm 1.8.5 and copy to my sdcard in path  bootloader/payloads/   , i use  deepsea 1.9.0 and my switch is unpatched ,  both sysnand and emunand are Hos 11.0.0.
when i choose to inject lockpick as a payload in rcm mode,  the screen display the main menu in lockpick 1.8.5,  
after i select to dump form sysnand or emunand  ,then  it must be occur unexpected remap entry chain failure !  
i have no idear because when i use lockpick 1.8.4 and Hos 10.2.0 in past  , everything is good.

**Comment by UL7RA** [comment]
This issue was already identified and the dev is working on it. #41

**Comment by paulzheng136** [comment]
thanks

**Comment by paulzheng136** [comment]
> This issue was already identified and the dev is working on it. See here: #41

thanks
