### ISSUE TITLE
blackscreen

### ISSUE THREAD

**Issue by 0xCCD** [shchmue/Lockpick_RCM#45]
I have an Erista console with SXCore

I haven't a NAND backup and stupidly installed v11.0.1 on my sysnand with ChoiDujourNX.

After doing this every try to run OFW, CFW or genuine boot ends in a blackscreen.

I've now tried to follow the https://suchmememanyskill.github.io/guides/unbrick/ tutorial and downloaded latest LockPick_RCM payload, unfortunately it can not read my keys. I choose read from sysnand and with slow mo video i was able to see what happens: 
![LockPick](https://user-images.githubusercontent.com/1156088/103048996-b89f8000-4590-11eb-8862-14b8d04c27a1.jpg)

After this it reboots automatically and directly hangs on blackscreen too.

Any Idea how i can make it extract keys correctly ?

**Comment by shchmue** [comment]
Can you try with a different SD card?

**Comment by 0xCCD** [comment]
I tried and got now different result 
![IMG_20201224_124717__01](https://user-images.githubusercontent.com/1156088/103086955-53767980-45e6-11eb-9e21-7c5b563d6eb5.jpg)

A file is created but I can not unpack NCA Header with it:

Unable to create NCA class. Is your keyset file valid?
Error: Unable to decryp NCA header. The file is not an NCA file or the header key is incorrect

**Comment by shchmue** [comment]
You’ll need to unzip the Atmosphere and Hekate releases onto the second SD and try again

**Comment by 0xCCD** [comment]
I did and than I have same issue as before it immediately goes to blackscreen after seeing this, I can't even click on power button 

![Screenshot_20201225-141651__01](https://user-images.githubusercontent.com/1156088/103135955-94d95880-46bc-11eb-929e-1efe6e548f5e.jpg)

Also I get this with biskeydump v9

![IMG_20201225_135825__01__01](https://user-images.githubusercontent.com/1156088/103135956-9571ef00-46bc-11eb-9689-b096f826d20a.jpg)

and hekate dump of package 1 / 2 only show this before it also goes to blackscreen 

![Screenshot_20201225-141915 (1)](https://user-images.githubusercontent.com/1156088/103135957-96a31c00-46bc-11eb-9434-c6000a8351fb.jpg)

**Comment by 0xCCD** [comment]
Managed it to get the my keys with this:
https://gbatemp.net/threads/running-atmosphere-on-erista-patched-sx-core-switch.574083/
Once iw as able to start atmosphere i could also extract keys via sept.

Followed this to restore a clean nand
https://suchmememanyskill.github.io/guides/unbrick/#mmc-rebuild

**Comment by shchmue** [comment]
I don't see anything special about the atmosphere guide, what was the missing element here?

**Comment by 0xCCD** [comment]
I guess creating emunand + pressing the cleanup button which allows 
atmosphere to boot

**Comment by shchmue** [comment]
ah, well thanks for letting me know and I'm glad it's working
