### ISSUE TITLE
1.9.0 Lockpick  does not remove keys 

### ISSUE THREAD

**Issue by Anarhist8BIT** [shchmue/Lockpick_RCM#47]
Hello! why lockpick.bin on 2v switch 11.0.1 always removes the same keys? , without bis0.1.2.3? there is also no tset key, HWI, SBK.

**Comment by shchmue** [comment]
on Mariko consoles, Lockpick cannot dump SBK, and no TSEC is ever generated on these consoles. are the `bis_key_00` through 02 missing in your `prod.keys` file after running?

**Comment by Anarhist8BIT** [comment]
boot0 is corrupted on the console, in order to create normal boot and firmware I need to remove the keys, but I cannot do it, I tried it on different consoles, the same keys are always removed.

**Comment by shchmue** [comment]
You will need to flash a boot0 appropriate for this console (specific to either Erista or Mariko) to use Lockpick_RCM. Seek help in a support community such as Discord's Nintento Homebrew server.
