### ISSUE TITLE
No bis_keys readable under Lockpick_RCM v1.9.0 on Mariko revision

### ISSUE THREAD

**Issue by muxi1** [shchmue/Lockpick_RCM#48]
Hi shchmue,
I used Lockpick_RCM 1.9.0 under an Erista v1 and a Mariko to read out the prod.keys. With the Erista v1, all keys are read out completely as usual. As is known, not all keys can be read out under the Mariko, but what I noticed is that no bis_keys can be read out under the RCM version. Under the NRO version, however, this is possible. Is there possibly a bug here? (Sorry for my bad english)

**Comment by shchmue** [comment]
You must use Spacecraft NX as the SX loader causes keyslot problems and makes it impossible for Lockpick_RCM to derive the keys

dup of https://github.com/shchmue/Lockpick_RCM/issues/46
