### ISSUE TITLE
can't get partialaes.keys 

### ISSUE THREAD

**Issue by Anarhist8BIT** [shchmue/Lockpick_RCM#49]
Why isn't the partialaes.keys file generated on nintendo lite?
prod.keys got 118 as expected
https://sun9-44.userapi.com/impg/WzlT6niDhGzMp8HrytP5PnnrtTkkfVehWJz17A/viV7ctyc9aQ.jpg?size=1215x2160&quality=96&proxy=1&sign=9d23836c69d40e9db170df899175cc34&type=album

**Comment by shchmue** [comment]
I see the problem. Can you confirm that this works?
[Lockpick_RCM.zip](https://github.com/shchmue/Lockpick_RCM/files/5772911/Lockpick_RCM.zip)

**Comment by shchmue** [comment]
should be addressed by this commit which just changes the code flow https://github.com/shchmue/Lockpick_RCM/commit/b77d42e8e3379e7a95249273f986213f25ed3a3f

**Comment by Anarhist8BIT** [comment]
I see the problem. Can you confirm that this works?
Lockpick_RCM.zip

this lockpick won't start

**Comment by Anarhist8BIT** [comment]
I see the problem. Can you confirm that this works?
Lockpick_RCM.zip 

thanks friend, with this lockpick got partialaes.keys

**Comment by shchmue** [comment]
nice, glad it worked
