### ISSUE TITLE
I can't create firmware 11.0.1 on mariko

### ISSUE THREAD

**Issue by Anarhist8BIT** [shchmue/Lockpick_RCM#50]
is it possible to create 11.0.1 with the received keys on mariko? by the EmmcHaccGen program?
https://sun9-11.userapi.com/impg/PtxUGsJuhTZU98kr8LtMqWH1oFG60Jr6zIF8YQ/WO3wdfDFy70.jpg?size=1215x2160&quality=96&proxy=1&sign=95f2326a88437874beb038aac5278bd0&type=album

**Comment by shchmue** [comment]
as far as i know, emmchaccgen does not generate correct mariko boot0 and correct boot0 is required for lockpick_rcm

**Comment by Anarhist8BIT** [comment]
boot0 can be taken from another console on the same firmware version, they are not unique. the main thing is to generate a system partition based on native keys

**Comment by shchmue** [comment]
yes if you take boot0 from another mariko console then lockpick_rcm will generate correct bis keys
