### ISSUE TITLE
Please Support firmware 11.0.1

### ISSUE THREAD

**Issue by Sorata** [shchmue/Lockpick_RCM#52]
Just like the title.
Thank you~

**Comment by shchmue** [comment]
all firmware versions are supported. if you’re having an issue please post the details

**Comment by Sorata** [comment]
![1](https://user-images.githubusercontent.com/2240909/108677907-4cf07980-7525-11eb-8cbf-676647160b88.jpg)
![2](https://user-images.githubusercontent.com/2240909/108677910-4eba3d00-7525-11eb-8f70-7d0f055f5ce7.jpg)


It seems showed not right.
Any idea?

**Comment by shchmue** [comment]
what happened before this? did you use choidujournx on a mariko console?

**Comment by Sorata** [comment]
There are two example:
1.mariko device 11.0.1 No ChoiDujourNX (System auto update)
2.Early RCM device 11.0.1 No ChoiDujourNX (System auto update)

Both have the same error.
Weird.

**Comment by Sorata** [comment]
Early RCM device use Atmosphere  to downgrade 11.0.0.
Lockpick_RCM work.

**Comment by shchmue** [comment]
I see my mistake in the first screenshot- i didn’t validate the pkg1 check. as for you, your problem is that your boot0 is bad for whatever reason and you need to reflash it using emmchaccgen

**Comment by Sorata** [comment]
> 
> 
> I see my mistake in the first screenshot- i didn’t validate the pkg1 check. as for you, your problem is that your boot0 is bad for whatever reason and you need to reflash it using emmchaccgen

Thamk you for your reply. I'll try later.

**Comment by Sorata** [comment]
Not work.
But may be it just my problem, and I will pay attention on it.
