### ISSUE TITLE
Error on booting

### ISSUE THREAD

**Issue by ninetalescommander** [shchmue/Lockpick_RCM#54]
Whenever I run Lockpick_RCM, I get the error "Unknown pkg1 version", am I doing something wrong?

**Comment by shchmue** [comment]
does your console boot? do you have the files from the a recent release of Atmosphere on your SD?

**Comment by ninetalescommander** [comment]
Yeah, console boots fine and even all other programs work fine, it's literally just Lockpick_RCM that doesn't work.

**Comment by shchmue** [comment]
Does the main menu detect your keyblob versions correctly? Can you send a picture of the screen when it fails?

**Comment by ninetalescommander** [comment]
![Uploading IMG_20210402_163721.jpg…]()

**Comment by ninetalescommander** [comment]
[IMG_20210402_163721](https://user-images.githubusercontent.com/53667865/113430564-4d0c5080-93d2-11eb-9a13-67393a53169f.jpg)

**Comment by shchmue** [comment]
that's a very old version of Lockpick_RCM! try the latest

**Comment by ninetalescommander** [comment]
I am, this is what I get.
Just to make sure; I am meant to be loading Hekete > Payloads > Lockpick_RCM, right?

**Comment by ninetalescommander** [comment]
Update: Never mind, I worked it out. I was downloading the latest and wasn't putting it in Payloads so I was still using the older one.
