### ISSUE TITLE
Add support for 12.0.2

### ISSUE THREAD

**Issue by Aura314** [shchmue/Lockpick_RCM#55]
Hello I have a problem with Lockpick_Rcm since firmware 12.0.2 is out from nintendo lockpick_Rcm tells me that the sysnand is unkown so you can no longer read the keys from the sysnand help me for support 12.0.2 thanks 
![IMG_1841](https://user-images.githubusercontent.com/83787307/117984770-680aa280-b338-11eb-9d48-fdcf96fd3ee4.JPG)

**Comment by lowburger** [comment]
You must wait for lockpick rcm update for recognize 12.0.2

**Comment by shchmue** [comment]
Will fix this shortly.

**Comment by shchmue** [comment]
done https://github.com/shchmue/Lockpick_RCM/commit/93909f149ef36ccdef1ac9e72849a101e3133b5d
