### ISSUE TITLE
pkg1 error on v1.9.2

### ISSUE THREAD

**Issue by taro-omilktea** [shchmue/Lockpick_RCM#56]
I'm getting the following error upon trying to dump from SysNAND with the new version of Lockpick -
`Unknown pkg1 version.
 Make sure you have the latest Lockpick_RCM`
My SD card is fully updated with the latest release of atmosphere and hekate. I've tried troubleshooting a bit by making sure all of my files are updated, and still no luck.

**Comment by shchmue** [comment]
what version of firmware do you have?

**Comment by taro-omilktea** [comment]
12.0.2

**Comment by shchmue** [comment]
can you attach a photo of the main lockpick_rcm screen and the error screen?

**Comment by taro-omilktea** [comment]
![image1](https://user-images.githubusercontent.com/84354567/118564431-7b997d00-b72d-11eb-8d9e-087aad1aefcd.jpg)
![image2](https://user-images.githubusercontent.com/84354567/118564441-7dfbd700-b72d-11eb-8655-a820140f8120.jpg)

**Comment by shchmue** [comment]
is this an erista or mariko console? does it boot?

**Comment by taro-omilktea** [comment]
erista console. it wont boot in anything other than rcm at the moment

**Comment by shchmue** [comment]
any idea what happened to it? this appears to have pkg1 flashed misaligned on the nand and i suspect there's not a problem with lockpick_rcm

**Comment by taro-omilktea** [comment]
had an [NXBOOT] error when updating atmosphere so i'm assuming this is bigger than i initially thought

**Comment by shchmue** [comment]
yeah, sounds like a problem with whatever is on the nand. sorry to hear that
