### ISSUE TITLE
8.1.0 Possibly not supported

### ISSUE THREAD

**Issue by eXhumer** [shchmue/Lockpick_RCM#6]
Lockpick_RCM is giving "Unknown pkg1 version." when trying to use on 8.1.0.

**Comment by shchmue** [comment]
Yeah, I'm updating it right now. It's working fine with new Sept, now working on adding emunand support. Shouldn't be long.

**Comment by shchmue** [comment]
Fixed in 54d14196e0a9ad806dfa9e1c59dcd064c8312a71

**Comment by nickkeane** [comment]
Getting same issue w/ 9.1.0 - "Unknown pkg1 version". Very recent system update.

**Comment by shchmue** [comment]
see https://github.com/shchmue/Lockpick_RCM/issues/15
