### ISSUE TITLE
Black screen after attempting to dump SYSNAND keys

### ISSUE THREAD

**Issue by joshcampbell191** [shchmue/Lockpick_RCM#60]
Currently getting a black screen when attempting to dump 12.1.0 SYSNAND keys after updating to the latest version of Atmosphere (0.19.5) / Hekate (5.5.8) / Lockpick RCM (1.9.3). Is there anything else I can do to further debug this issue?

**Comment by shchmue** [comment]
these are tricky, you'd want to launching the payload with another method (if chainloading from hekate, push directly from a payload launcher or vice versa) or try a different SD card

**Comment by joshcampbell191** [comment]
Thanks for the response. I've already tried loading it from a different launcher. I'll let you know how it goes with a different SD card.
