### ISSUE TITLE
Blank screen and then nothing

### ISSUE THREAD

**Issue by rzbuno** [shchmue/Lockpick_RCM#62]
When following the usage guidelines, I always get a really quick log screen and then a blank screen with no furthermore behavior.

<h1>Environment</h1>

- LockPick_RCM 1.9.3
- Firmwares 12.0.3 and 12.1.0
- atmosphere-0.19.5-master-9df13781c
- hbl-2.4.1
- hbmenu-3.4.0
- hekate v5.5.8
- Nyx v1.0.5

<h1>Screenshots</h1>

Screenshot 1
![cap_a](https://user-images.githubusercontent.com/64307270/125107580-45e79380-e0e1-11eb-8a39-c480f003e7a8.png)

Screenshot 2
![cap_b](https://user-images.githubusercontent.com/64307270/125107585-46802a00-e0e1-11eb-8d67-4a2ba1cdaf18.png)

<h1>MicroSD Filelist</h1>

Filelist
[files.txt](https://github.com/shchmue/Lockpick_RCM/files/6792653/files.txt)

**Comment by rzbuno** [comment]
I finally succeeded using TegraRCM RCM loader with a microSD without /sept/.

**Comment by shchmue** [comment]
that's less desirable since you won't get any new master keys. if you need those for anything, it's worth trying with Sept on a fresh SD card
