### ISSUE TITLE
getting errors with hwfly modchip

### ISSUE THREAD

**Issue by aiokswhatever** [shchmue/Lockpick_RCM#63]
hi. I got new hwfly chip and trying to backup keys.
I got fresh atmospere in the sdcard and checked that sept folder exists

I'm getting the next output
![IMG_6339 2](https://user-images.githubusercontent.com/45019940/126575635-26157067-dd86-4b12-a7c3-66bac0114e51.jpg)

am I doing something wrong?
thanks

**Comment by Masamune3210** [comment]
Did you boot atmosphere at least once first? I'm pretty sure some things have to be dumped first which atmosphere does automatically on boot if needed. Could be wrong though

**Comment by shchmue** [comment]
> hi. I got new hwfly chip and trying to backup keys.
> I got fresh atmospere in the sdcard and checked that sept folder exists
> 
> I'm getting the next output
> ![IMG_6339 2](https://user-images.githubusercontent.com/45019940/126575635-26157067-dd86-4b12-a7c3-66bac0114e51.jpg)
> 
> am I doing something wrong?
> thanks

are you using spacecraft nx? if not that might be the problem. if you’re on 12.1.0 though i need to build an update to address this

> Did you boot atmosphere at least once first? I'm pretty sure some things have to be dumped first which atmosphere does automatically on boot if needed. Could be wrong though

this is not relevant to lockpick_rcm

**Comment by aiokswhatever** [comment]
> Did you boot atmosphere at least once first? I'm pretty sure some things have to be dumped first which atmosphere does automatically on boot if needed. Could be wrong though

Seems to be the thing! Thank you!
Was going through steps and it says back ups first. So after installing emuNAND it took 100+ keys.

Thanks for replies guys!
