### ISSUE TITLE
mariko with spacecraft flashed

### ISSUE THREAD

**Issue by tiagofcp** [shchmue/Lockpick_RCM#64]
Hi can some help im getting this:

![232378126_2905748649675448_8149159813688037153_n](https://user-images.githubusercontent.com/12100048/128556489-1b4972da-d21b-4968-96a5-8e47f4225151.jpg)

i cant get the bis keys to work on nxnandmanager

**Comment by tiagofcp** [comment]
another thing i noticed the prod.keys file that was generated is exact the same as the one available on this issue #46 only the device_key_4x is different.

Also before flashing spacecraft the result was the same

**Comment by suchmememanyskill** [comment]
I built lockpick from the latest commit in master for them, and that seems to dump the keys correctly. They are using a mariko unit. See also <https://github.com/suchmememanyskill/TegraExplorer/issues/45>.

I don't know what actually fixed it though, just that a build from the latest commit fixed this.

**Comment by shchmue** [comment]
> I built lockpick from the latest commit in master for them, and that seems to dump the keys correctly. They are using a mariko unit. See also [suchmememanyskill/TegraExplorer#45](https://github.com/suchmememanyskill/TegraExplorer/issues/45).
> 
> I don't know what actually fixed it though, just that a build from the latest commit fixed this.

yeah i fixed it in https://github.com/shchmue/Lockpick_RCM/commit/db453b961b8a353db9eeb86250a66409a22a41af and never got around to building it. can't believe it's been a month... i should roll a release
