### ISSUE TITLE
Error 4294967291 running keygen

### ISSUE THREAD

**Issue by Entretoize** [shchmue/Lockpick_RCM#66]
I have a Erista switch I'm trying to get any game working after migrating from sxos to athmosphere and in my hard way of getting things to work I'm trying to generate the needed keys with lockpick_rcm, but when doing "dump from sysnand" or "dump from emunand" I get this message:

```
MMC init... done in 227591 us
ERROR 4294967291 running keygen.

Unable to run keygen.
```

What is the problem ?

**Comment by Entretoize** [comment]
I tried both launching from SX boot and from Hekate payload menu, I'm not sure it is what you mean.
Maybe it can help, I retied with v1.8.5 as I have firmware 11 and I'm not sure if it's ok as there's red lines:


```
MMC init... done in 31758 us 
on firmware 7.x+ but sept missing. 
Skipping new key derivation... 
TSEC key(s)... done in 22834 us
Keyblob 0 corrupt.
Keyblob 1 corrupt.
Keyblob 2 corrupt.
Keyblob 3 corrupt.
Keyblob 4 corrupt.
Keyblob 5 corrupt.

Master keys.. done in 6549 us 
FS keys... done in 187 us
Missing Fs keys. Skipping Es/SSL keys.

   Found 63 keys.

Lockpick totally done in 64969 us 
Found through Master_key_0A.
Wrote 3829 bytes to sd:/switch/prod.keys
```

**Comment by shchmue** [comment]
[Lockpick_RCM.zip](https://github.com/shchmue/Lockpick_RCM/files/7084838/Lockpick_RCM.zip)
can you try this payload and let me know specific status codes?

**Comment by Entretoize** [comment]
That gives me status D0D0D0D0 several times

**Comment by shchmue** [comment]
is this a SX modchip on a patched Erista or just the SX payload menu or whatever it's called? what i mean is can you just push a payload directly from a computer/phone instead of using the SX or is your console patched and requires the modchip? if it's chipped you might need to flash spacecraft-nx

**Comment by shchmue** [comment]
also try (latest) hekate in nyx go to Console Info on top bar -> HW & Fuses in bottom left -> CAL0 Info top middle, does that work?

**Comment by Entretoize** [comment]
I have a Sx core inside the switch my boot.dat is the sx os one.
I don't find how to send a payload from my computer, I'm not able to mount emmc as USB mass storage...

Yes CAL0 Info gives several infos.

**Comment by shchmue** [comment]
thanks for your patience, can you try this payload and let me know the number it tells you to record
[Lockpick_RCM.zip](https://github.com/shchmue/Lockpick_RCM/files/7087264/Lockpick_RCM.zip)

**Comment by Entretoize** [comment]
That gives `TST0 00000000`

**Comment by shchmue** [comment]
[Lockpick_RCM.zip](https://github.com/shchmue/Lockpick_RCM/files/7091937/Lockpick_RCM.zip)
this one produces even more diagnostic numbers

**Comment by Entretoize** [comment]
Thank you however I did a fresh install using Kefir that does all the job, and it works. Thank you for your time !

**Comment by shchmue** [comment]
i know this is at this point unrelated to your original problem but could i convince you to run and report from the latest payload so i can help others avoid this lockpick_rcm issue in the future?

**Comment by Entretoize** [comment]
Sure, I am a developer too and I understand, I ran it again and this is the text I get:
[Lockpick_RCM v1.9

TST0 00000000
TST1 3FFE814C
TST2 00000000
TST3 2000FEEF
TST4 2000FEEF
TST5 04D102C8
TST6 84D07326
TST7 828EC5FA
TST8 01E42049
TST9 0FE9F0DD

**Comment by shchmue** [comment]
thanks. i guess something about your pack fixed the issue
