### ISSUE TITLE
bis_key_sources

### ISSUE THREAD

**Issue by impeeza** [shchmue/Lockpick_RCM#67]
Hi, I don't know if is a bug or a correction to past versions, but on the prod.key file generated before version 1.9.4 the section for bis keys, each one was named:  bis_key_source now are named: bis_key_sources (with a extra «s» at end).  The name changed?

regards, thanks a lot for all your work.

**Comment by shchmue** [comment]
oh! good catch, i will fix that, thank you

**Comment by shchmue** [comment]
https://github.com/shchmue/Lockpick_RCM/commit/8fa8941cd26e2479db03c0e443d4c6f280de14e0 here's the fix
