### ISSUE TITLE
Reboot to hekate doesn't work after keygen

### ISSUE THREAD

**Issue by OrGoN3** [shchmue/Lockpick_RCM#68]
I have latest hekate 5.6.0 and latest nyx. Just tried latest lockpick rcm. Works great. Except reboot to hekate. Reboot to hekate menu option works great if you select it before dumping keys. Once you dump keys, selecting Reboot to Hekate just reloads the screen. Selecting a Payload works just fine, even if that Payload is hekate.

I verified I have an update.bin in bootloader and that it loads hekate just fine.

**Comment by shchmue** [comment]
Whoops! Thanks for alerting me to this. Fixed 69f8c8f33993de51dca28a2a4bf9dda0c691f0f0
