### ISSUE TITLE
tried to dump my keys on 8.1.0 but it hangs on SEPT

### ISSUE THREAD

**Issue by goffrier** [shchmue/Lockpick_RCM#7]
hi,i tried to dump my keys with the latest lockpick rcm and i used the latest sept provided in the latest release of ams but wen i hit vol+ to reboot to sept it hangs on sept forever

**Comment by shchmue** [comment]
what firmware version are you on

**Comment by goffrier** [comment]
8.1.0

**Comment by goffrier** [comment]
release zip on sd

**Comment by goffrier** [comment]
and i extracted all the release zip content on sd

**Comment by goffrier** [comment]
sd card is on exfat

**Comment by shchmue** [comment]
could be corrupt SD filesystem. try another card or try backing up and reformatting to fat32
