### ISSUE TITLE
Invalid keys dumped for some installed titles since >=1.9.5 update

### ISSUE THREAD

**Issue by petras607** [shchmue/Lockpick_RCM#72]
Some titles installed to SD card will have an invalid key dumped to prod.keys. This affects things like being able to dump these titles' contents via nxdumptool or being able to play those titles in emulators like yuzu. No errors are being reported during the key dumping process. The affected titles are perfectly playable on Switch itself.

It's not title dependant, since judging by issues in ndxumptool's GitHub page, each person that can't dump their content reports different titles. It has to be something within the key itself that breaks the derivation process.

I've deduced it's at least 1.9.5 that introduced this bug because I've been able to properly dump one of my affected titles (Sonic Colors Ultimate) soon after launch, but now I can't do it because of this bug.

I'm running on the first variant of Switch (purchased in late 2017), FW 13.2.1, Atmosphere 1.2.6, hekate 5.7.0, nxdumpptool 1.1.14, Lockpick_RCM 1.9.6.

**Comment by petras607** [comment]
Yes I am, Courtroom#7687.

**Comment by shchmue** [comment]
Conducted troubleshooting with user over Discord and found that Lockpick_RCM is doing its job, issues appear to be with Yuzu and legacy nxdumptool
