### ISSUE TITLE
I can't get tittles.key

### ISSUE THREAD

**Issue by Richter-malaga** [shchmue/Lockpick_RCM#73]
Hello! I Am trying to get the keys for playing cotton saturn emulator, but When I usé lockpick payload last versión he found 0 tittles.key to me.. Only others keys they are found.. Dev.key and others but not tittles.key.. Why? I have latest firmware and micro sd are in exfat.. I try with a diferent micro sd card formated in fat32 but the same problem only found the others keys but not tittles.key

**Comment by shchmue** [comment]
Is the game installed on your console? Is it on sysnand or emunand and are you dumping keys for the corresponding nand?
