### ISSUE TITLE
bis_key_02 and 3 come back as the same

### ISSUE THREAD

**Issue by TMNT0527** [shchmue/Lockpick_RCM#75]
I have tested this on 3 mariko units so far. When prod keys are dumped bis_key_02 and 03 are the same and there is no location for Bis_key_03 (bis_key_source_03)

**Comment by TMNT0527** [comment]
I do not have an unpatched one. I have been trying to use bis_key_03 and it gives me an error when trying to use it.

**Comment by shchmue** [comment]
All consoles will produce identical bis keys 02 and 03, my code doesn't even derive them separately, it just copies the result from one to the other. It is the same result in actual firmware, and is the correct key for decrypting the USER partition.
