### ISSUE TITLE
lockpic Version 1.9.8

### ISSUE THREAD

**Issue by oresterosso75** [shchmue/Lockpick_RCM#79]
Does this version support the new firmware 15.0.0?
I encountered problems extracting the 0E keys

**Comment by relm** [comment]
Try compiling from source, support for 15.0.0 was just recently committed.

**Comment by oresterosso75** [comment]
> Prova a compilare dal sorgente, il supporto per 15.0.0 è stato eseguito di recente.

unfortunately I don't have the knowledge to do this.
Will you release a compiled version with the new update?

**Comment by shchmue** [comment]
i will create a release when this issue is resolved https://github.com/shchmue/Lockpick_RCM/issues/78

**Comment by oresterosso75** [comment]
> creerò una versione quando questo problema sarà risolto #78

thanks, i will wait patiently 😀
