### ISSUE TITLE
Not working on FW 9.0.0

### ISSUE THREAD

**Issue by eXhumer** [shchmue/Lockpick_RCM#8]
Title self explanatory.

**Comment by james-d-elliott** [comment]
Yes, new tsec fw last I heard, need to wait for a new sept probably.

**Comment by shchmue** [comment]
Yes, once new Sept is out I can update

**Comment by Mar2ck** [comment]
new sept is out https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.9.4

**Comment by shchmue** [comment]
Yeah just a little more testing and it's ready

**Comment by shchmue** [comment]
Done and released 34890f00258475f129a7629bc9bf7a5e8168886d
