### ISSUE TITLE
Update for 15.0.1?

### ISSUE THREAD

**Issue by bonxz** [shchmue/Lockpick_RCM#82]
Update for 15.0.1?

**Comment by Masamune3210** [comment]
15.0.1 didn't touch anything important when it comes to the keys, latest should work fine if it supports 15

**Comment by shchmue** [comment]
indeed no update is needed, all available keys are supported by v1.9.9

**Comment by bonxz** [comment]
cant start cuz of "unknown pkg1 version"

**Comment by shchmue** [comment]
this program doesn’t print such an error, or at least it hasn’t in several versions
