### ISSUE TITLE
No Option to See SSL RSA key dumping?

### ISSUE THREAD

**Issue by Bonethugs1980** [shchmue/Lockpick_RCM#83]
I had this installed awhile back, but didn't realise it had the SSL RSA key dumping usage.  However, when I re-checked to see this, there is no such option.  

My switch is the earlier model XAJ that was 'Unpatched' etc, so it's fully hacked with latest Atmosphere 1.4.0 and Hekate 6.0.1 with no issues, have used RCM previously to dump the usual keys, but cannot see anything about the SSL RSA cert on this latest release.

The following is shown directly in Lockpick v1.9.9:

'Dump from SynsNAND'
'Dump from EmuNAND' [greyed out]

'Dump Amibo Keys'
'Dump Mariko Partials (required reboot)' [Greyed out] (Don't have Mariko Switch, so this shouldn't be an issue?)

From 'Payloads' down to 'Power Off' shown as usual.

Am I missing something?

**Comment by shchmue** [comment]
It dumps the key by default. It’s in your key file if you used the latest version. It doesn’t dump the cert.

**Comment by Bonethugs1980** [comment]
Thanks for the explanation shchmue.
