### ISSUE TITLE
Error: Couldn't set master_key_00

### ISSUE THREAD

**Issue by ClementNerma** [shchmue/Lockpick_RCM#84]
Hi!

I tried to use this program today and got the following error when trying to build PRODINFO from donor:

```
Dumping keys...
Unable to derive master keys for prod.
Master keys... done in 1869 us
Keygen part done in 2545 us

Couldn't set master_key_00

Done in 4136 us
```

And no file is generated on the SD card.

Do you know why this happens?

I'm on a Switch Lite if that helps.

**Comment by shchmue** [comment]
These errors aren't from my software.
