### ISSUE TITLE
[bug] Reboot to OFW doesn't work for AutoRCM

### ISSUE THREAD

**Issue by Yoti** [shchmue/Lockpick_RCM#86]
It goes to the RCM mode instead of OFW.
I suggest disable or add a note to the item.

**Comment by My1** [comment]
well AutoRCM literally breaks the console in a controlled manner so it wont boot normally.

**Comment by shchmue** [comment]
Lockpick_RCM retains the naming from the hekate codebase. Anyone with AutoRCM enabled should ideally understand what it does - the only thing that can be done from baremetal to get to the OS with AutoRCM enabled is to chainload a payload that launches the OS, Lockpick_RCM can't get around AutoRCM.

**Comment by Yoti** [comment]
You may hide or disable this item from menu when detecting AutoRCM.
