### ISSUE TITLE
Get Tegra keys.... Failed. I cannot run nor install NSPs

### ISSUE THREAD

**Issue by kotapo** [shchmue/Lockpick_RCM#9]
Hello guys,
I'm super worried because sisnce yesterday I updated atmosphere, Hekate and everything (supposedly correctly) but I keep getting this key issue that won't allow me to play nor install my nsp files. I was reading some previous posts about this and realized that there's supposed to be /backups folder in my SD that is not there. At the Lockpick.rcm section in Hekate I do get through the process without any problems. It generates 140 keys including the Tegra one(s) or at least it says "done". However when I go to the lockpicks section on the homebrew it says I have 72 keys and it keeps showing me the Get Tegra keys.... Failed.
I'm totally new to this and super worried because I can't make it work.

**Comment by shchmue** [comment]
there really isn't any reason for homebrew to require keys but that's probably not a relevant discussion for you

it's possible whatever other program you're using doesn't support new keys or something. you did everything right as far as my programs are concerned
