### ISSUE TITLE
shchmue the THREAD WAS FOR YOU BEFORE THE IDIOT CAME!!!!!!

### ISSUE THREAD

**Issue by TheTrueLordOfIllusions** [shchmue/Lockpick_RCM#91]
I NEVER STARTED ANY SH*T!!!!

ALL I ASKED WAS WHERE YOU DMCA'd

WHY AM I GETTING MY SH*T ATTACKED FOR ASKING YOUUUU!!!! A  QUSTION ( I EVEN STATED IN THE VERY BEGINNING THE THREAD IS FOR YOU)

don't DELETE MY THREAD AND MAKE MEEE!!!! LOOK BAD FOR ASKING YOU SOMETHING

WHEN SOME JACK*SS COMES IN AND HIGHJACKS SOMETHING TO TRY TO ARGUE!!!

IS THIS REAL!!! OR NOT
[2023-05-04-nintendo-4.txt](https://github.com/shchmue/Lockpick_RCM/files/11416062/2023-05-04-nintendo-4.txt)

**Comment by Masamune3210** [comment]
Yes....the best way to get your question asked is definitely to insult and yell at the person who you are asking it to....

**Comment by TheTrueLordOfIllusions** [comment]
FORGET IT IF YOU WERE THEN I HOPE YOUR ENTIRE PROJECT IS BANNED

I WILL STILL HAVE MY KEYS SO I LITEREALLY DON"T CARE EITHER WAY

AND I KNOW THE FORKED OPEN SOURSE CODE WILL KEEP UP SOMEWHERE elSe

**Comment by TheTrueLordOfIllusions** [comment]
THEN TTHY SHOULD N"T DELETE MY THREEAD

**Comment by TheTrueLordOfIllusions** [comment]
some idiot came in so shemu thought i was arguenting then delteted it

**Comment by TheTrueLordOfIllusions** [comment]
so NOW IM PISSED

**Comment by TheTrueLordOfIllusions** [comment]
FINE DELETE THIS ONE TOO AGAIn

BUT DON"T YOUDTFOgjdfghbndfopuspfndogu[afngijorelsfgardhelnkfgjslf vgasDJ:kfvsdnsef fdd DARE SAY I STARTED A ARGUEMENT WITH SOMEONE

**Comment by TheTrueLordOfIllusions** [comment]
> Yes....the best way to get your question answered is definitely to insult and yell at the person who you are asking it to....

YOU KNEW EXACTLY WHAT HAPPPEND

**Comment by Masamune3210** [comment]
Please go somewhere else if you are going to continue this, either that or at least stop throwing a fit.

**Comment by TheTrueLordOfIllusions** [comment]
> Please go somewhere else if you are going to continue this, either that or at least stop throwing a fit.

NO I WON"T

[2023-05-04-nintendo-4.txt](https://github.com/shchmue/Lockpick_RCM/files/11416081/2023-05-04-nintendo-4.txt)

THIS ENTIRE OPEN SOURCE PROJECT IS DMCA'd ALL I ASKED THE DEV IS FOR CONFORMAITON

THEN MY THREAD GOT DELETED BECAUSE SOMEONE ELSE CAME IN A ND ARGUED  SO OS   SHUt UP

**Comment by IsaacMarovitz** [comment]
jesus what is happening

**Comment by Masamune3210** [comment]
A child throwing a tantrum
